=== DmitryPoverov/Epam-new/src/main/resources/vouchersSchema.xsd
<xs:schema attributeFormDefault="unqualified" targetNamespace="test" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="touristVouchers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="familyVoucher">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="type"/>
                            <xs:element type="xs:string" name="country"/>
                            <xs:element type="xs:byte" name="numberOfDays"/>
                            <xs:element type="xs:string" name="transport"/>
                            <xs:element name="hotelCharacteristics">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:byte" name="numberOfStars"/>
                                        <xs:element name="mealsIncluded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="mealType"/>
                                                </xs:sequence>
                                                <xs:attribute type="xs:string" name="available"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element type="xs:string" name="roomType"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:short" name="cost"/>
                            <xs:element type="xs:byte" name="numOfFamilyMembers"/>
                        </xs:sequence>
                        <xs:attribute type="xs:byte" name="id"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="businessVoucher">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="type"/>
                            <xs:element type="xs:string" name="country"/>
                            <xs:element type="xs:byte" name="numberOfDays"/>
                            <xs:element type="xs:string" name="transport"/>
                            <xs:element name="hotelCharacteristics">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:byte" name="numberOfStars"/>
                                        <xs:element name="mealsIncluded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="mealType"/>
                                                </xs:sequence>
                                                <xs:attribute type="xs:string" name="available"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element type="xs:string" name="roomType"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:short" name="cost"/>
                            <xs:element type="xs:byte" name="numOfMeetings"/>
                        </xs:sequence>
                        <xs:attribute type="xs:byte" name="id"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DmitryPoverov/Epam-new/src/main/resources/vouchers.xml
<?xml version="1.0" encoding="UTF-8"?>
<touristVouchers xmlns="test"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="test vouchersSchema.xsd">

    <familyVoucher id="11">
        <type>Weekend</type>
        <country>Mexico</country>
        <numberOfDays>10</numberOfDays>
        <transport>bus</transport>
        <hotelCharacteristics>
            <numberOfStars>5</numberOfStars>
            <mealsIncluded available="true">
                <mealType>AI</mealType>
            </mealsIncluded>
            <roomType>triple</roomType>
        </hotelCharacteristics>
        <cost>500</cost>
        <numOfFamilyMembers>3</numOfFamilyMembers>
    </familyVoucher>

    <businessVoucher id="22">
        <type>Business</type>
        <country>USA</country>
        <numberOfDays>2</numberOfDays>
        <transport>airplane</transport>
        <hotelCharacteristics>
            <numberOfStars>4</numberOfStars>
            <mealsIncluded available="true">
                <mealType>BB</mealType>
            </mealsIncluded>
            <roomType>double</roomType>
        </hotelCharacteristics>
        <cost>1000</cost>
        <numOfMeetings>2</numOfMeetings>
    </businessVoucher>

</touristVouchers>
